package auth

import (
	"errors"
	"fmt"

	"github.com/golang-jwt/jwt/v5"
)

var (
	ErrInvalidToken = errors.New("invalid token")
	ErrExpiredToken = errors.New("token expired")
	ErrMissingClaim = errors.New("missing required claim")
)

// Claims represents the JWT claims we expect
type Claims struct {
	Hash     string `json:"hash"`
	Name     string `json:"name,omitempty"`
	Username string `json:"username,omitempty"`
	UserType string `json:"user_type,omitempty"`
	IsAdmin  string `json:"is_admin,omitempty"`
	jwt.RegisteredClaims
}

// ValidateToken validates a JWT token and extracts the user ID from the 'hash' claim.
// Returns the user ID on success, or an error describing the failure.
func ValidateToken(tokenString, secret string) (string, error) {
	if tokenString == "" {
		return "", ErrInvalidToken
	}

	token, err := jwt.ParseWithClaims(tokenString, &Claims{}, func(token *jwt.Token) (any, error) {
		// Validate signing method
		if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, fmt.Errorf("unexpected signing method: %v", token.Header["alg"])
		}
		return []byte(secret), nil
	})

	if err != nil {
		if errors.Is(err, jwt.ErrTokenExpired) {
			return "", ErrExpiredToken
		}
		return "", fmt.Errorf("%w: %v", ErrInvalidToken, err)
	}

	if !token.Valid {
		return "", ErrInvalidToken
	}

	claims, ok := token.Claims.(*Claims)
	if !ok {
		return "", ErrInvalidToken
	}

	// Extract user_id from 'hash' claim
	userID := claims.Hash
	if userID == "" {
		return "", ErrMissingClaim
	}

	return userID, nil
}

// GenerateToken creates a JWT token for testing purposes.
// In production, tokens should be generated by your auth service.
func GenerateToken(userID, secret string) (string, error) {
	claims := Claims{
		Hash: userID,
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	return token.SignedString([]byte(secret))
}
